spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appointments
    username: root
    password: pass@word1
  jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
server:
  port: 8085